alias path='echo -e ${PATH//:/\\n}'
alias lbt='date -d @$(grep ^btime /proc/stat | cut -d" " -f 2)'
alias upd='sudo apt-get update && sudo apt-get upgrade'
alias updd='sudo apt-get update && sudo apt-get dist-upgrade'
alias agi='sudo apt-get install $@'
alias aar='sudo add-apt-repository'
alias acp='sudo apt-cache policy'
git@github.com:miishke/dot_files.git
alias ms='sleep 1; xset dpms force off'
alias ah='history -a'
alias uh='history -n'
alias la='ls -lhA'
alias ap='export PATH=$HOME/miniconda3/bin:$PATH && export PS1="\[\e[94m\]\W \$\[\e[m\] "'
alias src='. ~/.bashrc'
alias sa='source activate'
alias sd='source deactivate'
alias ipy='ipython'
alias jn='jupyter notebook'
alias cls='conda list'
alias cie='conda info -e'
alias xclip='xclip -selection c'
alias fm='free -m'
alias fd='df -h
