alias path='echo -e ${PATH//:/\\n}'
alias lbt='date -d @$(grep ^btime /proc/stat | cut -d" " -f 2)'
alias upd='sudo apt-get update && sudo apt-get upgrade'
alias updd='sudo apt-get update && sudo apt-get dist-upgrade'
alias agi='sudo apt-get install $@'
alias aar='sudo add-apt-repository $@'
alias ms='sleep 1; xset dpms force off'
alias ah='history -a'
alias uh='history -n'
alias ap='export PATH=/home/XYZ/miniconda3/bin:$PATH && export PS1="\[\e[94m\]\W \$\[\e[m\] "'
alias ipn='ipython notebook'
